const ROUTES = {
    WELCOME: 'WELCOME',
    NEW_WALLET: 'NEW WALLET',
    NEW_WALLET_WORDS: 'NEW WALLET WORDS',
    RECOVER_WALLET: 'RECOVER WALLET',
    CREATE_PASSWORD: 'CREATE PASSWORD',
    LOGIN_SCREEN: 'LOGIN SCREEN',
    TERMS_SCREEN: 'TERMS SCREEN',
    RENTRYPASSWORD: 'RE-ENTRY PASSWORD',
    HOME: 'HOME-PAGE',
    PASSWORDLOGIN: 'PASSWORD-LOGIN',
    SETTING: {
        BASE: "SETTING",
        PASSCODE_RESET: "PASSCODE_RESET",
        PASSCODE_RE_ENTER: "PASSCODE_RE_ENTER"
    }
}

export default ROUTES