const ROUTES = {
    WELCOME: 'WELCOME',
    NEW_WALLET: 'NEW WALLET',
    NEW_WALLET_WORDS: 'NEW WALLET WORDS',
    RECOVER_WALLET: 'RECOVER WALLET',
    CREATE_PASSWORD: 'CREATE PASSWORD',
    LOGIN_SCREEN: 'LOGIN SCREEN',
    TERMS_SCREEN: 'TERMS SCREEN',
    RENTRYPASSWORD: 'RE-ENTRY PASSWORD',
}

export default ROUTES